export const notas = [
	{ nota: "D", espacio: false, numero: 32 },
	{ nota: "C#", numero: 31 },
	{ nota: "C", numero: 30 },
	{ nota: "B", espacio: true, numero: 29 },
	{ nota: "A#", numero: 28 },
	{ nota: "A", espacio: false, numero: 27 },
	{ nota: "G#", numero: 26 },
	{ nota: "G", espacio: true, numero: 25 },
	{ nota: "F#", numero: 24 },
	{ nota: "F", espacio: false, numero: 23 },
	{ nota: "E", espacio: true, numero: 22 },
	{ nota: "D#", numero: 21 },
	{ nota: "D", espacio: false, numero: 20 },
	{ nota: "C#", numero: 19 },
	{ nota: "C", espacio: true, numero: 18 },
	{ nota: "B", espacio: false, numero: 17 },
	{ nota: "A#", numero: 16 },
	{ nota: "A", espacio: true, numero: 15 },
	{ nota: "G#", numero: 14 },
	{ nota: "G", espacio: false, numero: 13 },
	{ nota: "F#", numero: 12 },
	{ nota: "F", espacio: true, numero: 11 },
	{ nota: "E", espacio: false, numero: 10 },
	{ nota: "D#", numero: 9 },
	{ nota: "D", espacio: true, numero: 8 },
	{ nota: "C#", numero: 7 },
	{ nota: "C", espacio: false, numero: 6 },
	{ nota: "B", espacio: true, numero: 5 },
	{ nota: "A#", numero: 4 },
	{ nota: "A", espacio: false, numero: 3 },
	{ nota: "G#", numero: 2 },
	{ nota: "G", espacio: true, numero: 1 },
]
