export const partituraSol = [
	{ nota: "D", espacio: true, numero: 19 },
	{ nota: "C", espacio: false, numero: 18 },
	{ nota: "B", espacio: true, numero: 17 },
	{ nota: "A", espacio: false, numero: 16 },
	{ nota: "G", espacio: true, numero: 15 },
	{ nota: "F", espacio: false, numero: 14 },
	{ nota: "E", espacio: true, numero: 13 },
	{ nota: "D", espacio: false, numero: 12 },
	{ nota: "C", espacio: true, numero: 11 },
	{ nota: "B", espacio: false, numero: 10 },
	{ nota: "A", espacio: true, numero: 9 },
	{ nota: "G", espacio: false, numero: 8 },
	{ nota: "F", espacio: true, numero: 7 },
	{ nota: "E", espacio: false, numero: 6 },
	{ nota: "D", espacio: true, numero: 5 },
	{ nota: "C", espacio: false, numero: 4 },
	{ nota: "B", espacio: true, numero: 3 },
	{ nota: "A", espacio: false, numero: 2 },
	{ nota: "G", espacio: true, numero: 1 },
]
