export const teclas =[
	{ nota: "C", color: "blanca", numero: 1, selected: false },
	{ nota: "C#", color: "negra", numero: 2, selected: false },
	{ nota: "D", color: "blanca", numero: 3, selected: false },
	{ nota: "D#", color: "negra", numero: 4, selected: false },
	{ nota: "E", color: "blanca", numero: 5, selected: false },
	{ nota: "F", color: "blanca", numero: 6, selected: false },
	{ nota: "F#", color: "negra", numero: 7, selected: false },
	{ nota: "G", color: "blanca", numero: 8, selected: false },
	{ nota: "G#", color: "negra", numero: 9, selected: false },
	{ nota: "A", color: "blanca", numero: 10, selected: false },
	{ nota: "A#", color: "negra", numero: 11, selected: false },
	{ nota: "B", color: "blanca", numero: 12, selected: false },
] /* [
	{ nota: "C", color: "blanca", numero: 1, selected: false },
	{ nota: ["do#", "reb"], color: "negra", numero: 2, selected: false },
	{ nota: "D", color: "blanca", numero: 3, selected: false },
	{ nota: ["re#", "mib"], color: "negra", numero: 4, selected: false },
	{ nota: "E", color: "blanca", numero: 5, selected: false },
	{ nota: "F", color: "blanca", numero: 6, selected: false },
	{ nota: ["fa#", "solb"], color: "negra", numero: 7, selected: false },
	{ nota: "G", color: "blanca", numero: 8, selected: false },
	{ nota: ["sol#", "lab"], color: "negra", numero: 9, selected: false },
	{ nota: "A", color: "blanca", numero: 10, selected: false },
	{ nota: ["la#", "sib"], color: "negra", numero: 11, selected: false },
	{ nota: "B", color: "blanca", numero: 12, selected: false },
] */
